export const EVENT_TYPE = {
  HEALTH_TALK: 'HEALTH_TALK',
  WELLNESS_EVENTS: 'WELLNESS_EVENTS',
  FITNESS_ACTIVITIES: 'FITNESS_ACTIVITIES',
}

export const EVENT_TYPE_LABEL = {
  [EVENT_TYPE.HEALTH_TALK]: 'Health Talk',
  [EVENT_TYPE.WELLNESS_EVENTS]: 'Wellness Events',
  [EVENT_TYPE.FITNESS_ACTIVITIES]: 'Fitness Activities',
}

export const TIME_FORMAT = 'YYYY-MM-DD HH:mm'
